"""create schema

Revision ID: d0e4a31fb1f8
Revises: 
Create Date: 2025-12-28 01:20:24.392734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0e4a31fb1f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_chat_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'usage_date', name='uq_ai_chat_usage_user_date')
    )
    op.create_index(op.f('ix_ai_chat_usage_usage_date'), 'ai_chat_usage', ['usage_date'], unique=False)
    op.create_index(op.f('ix_ai_chat_usage_user_id'), 'ai_chat_usage', ['user_id'], unique=False)
    op.create_table('create_post',
    sa.Column('sn', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('docid', sa.String(length=255), nullable=True),
    sa.Column('userid', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('parent_docid', sa.String(), nullable=True),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('privacy', sa.String(length=20), nullable=False),
    sa.Column('cached_amen_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('sn'),
    sa.UniqueConstraint('docid')
    )
    op.create_index('ix_create_post_datetime', 'create_post', ['datetime'], unique=False)
    op.create_index('ix_create_post_event', 'create_post', ['event'], unique=False)
    op.create_index('ix_create_post_parent_docid', 'create_post', ['parent_docid'], unique=False)
    op.create_index('ix_create_post_userid', 'create_post', ['userid'], unique=False)
    op.create_table('friend_invitation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requester_user_id', sa.String(length=120), nullable=False),
    sa.Column('target_user_id', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friend_invitation_requester_user_id'), 'friend_invitation', ['requester_user_id'], unique=False)
    op.create_index(op.f('ix_friend_invitation_target_user_id'), 'friend_invitation', ['target_user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(length=320), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_refresh_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('ix_refresh_subject', 'refresh_tokens', ['subject'], unique=False)
    op.create_table('tribe_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('activity_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_urls', sa.Text(), nullable=True),
    sa.Column('creator_userid', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tribe_activities_activity_id'), 'tribe_activities', ['activity_id'], unique=False)
    op.create_index(op.f('ix_tribe_activities_creator_userid'), 'tribe_activities', ['creator_userid'], unique=False)
    op.create_index('ix_tribe_activities_event_date', 'tribe_activities', ['event_date'], unique=False)
    op.create_table('user_friend',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('friend_user_id', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'friend_user_id', name='uq_user_friend_pair')
    )
    op.create_index(op.f('ix_user_friend_friend_user_id'), 'user_friend', ['friend_user_id'], unique=False)
    op.create_index(op.f('ix_user_friend_user_id'), 'user_friend', ['user_id'], unique=False)
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('tribe', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profile_email'), 'user_profile', ['email'], unique=True)
    op.create_index(op.f('ix_user_profile_user_id'), 'user_profile', ['user_id'], unique=True)
    op.create_table('post_amen',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_docid', sa.String(length=255), nullable=False),
    sa.Column('userid', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_docid'], ['create_post.docid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_docid', 'userid', name='uq_post_amen_post_user')
    )
    op.create_index(op.f('ix_post_amen_post_docid'), 'post_amen', ['post_docid'], unique=False)
    op.create_index(op.f('ix_post_amen_userid'), 'post_amen', ['userid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_amen_userid'), table_name='post_amen')
    op.drop_index(op.f('ix_post_amen_post_docid'), table_name='post_amen')
    op.drop_table('post_amen')
    op.drop_index(op.f('ix_user_profile_user_id'), table_name='user_profile')
    op.drop_index(op.f('ix_user_profile_email'), table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_index(op.f('ix_user_friend_user_id'), table_name='user_friend')
    op.drop_index(op.f('ix_user_friend_friend_user_id'), table_name='user_friend')
    op.drop_table('user_friend')
    op.drop_index('ix_tribe_activities_event_date', table_name='tribe_activities')
    op.drop_index(op.f('ix_tribe_activities_creator_userid'), table_name='tribe_activities')
    op.drop_index(op.f('ix_tribe_activities_activity_id'), table_name='tribe_activities')
    op.drop_table('tribe_activities')
    op.drop_index('ix_refresh_subject', table_name='refresh_tokens')
    op.drop_index('ix_refresh_expires_at', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_friend_invitation_target_user_id'), table_name='friend_invitation')
    op.drop_index(op.f('ix_friend_invitation_requester_user_id'), table_name='friend_invitation')
    op.drop_table('friend_invitation')
    op.drop_index('ix_create_post_userid', table_name='create_post')
    op.drop_index('ix_create_post_parent_docid', table_name='create_post')
    op.drop_index('ix_create_post_event', table_name='create_post')
    op.drop_index('ix_create_post_datetime', table_name='create_post')
    op.drop_table('create_post')
    op.drop_index(op.f('ix_ai_chat_usage_user_id'), table_name='ai_chat_usage')
    op.drop_index(op.f('ix_ai_chat_usage_usage_date'), table_name='ai_chat_usage')
    op.drop_table('ai_chat_usage')
    # ### end Alembic commands ###
