"""use json type for tribe images

Revision ID: e0c7a8abd8cd
Revises: d0e4a31fb1f8
Create Date: 2025-12-28 01:32:49.758039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0c7a8abd8cd'
down_revision: Union[str, Sequence[str], None] = 'd0e4a31fb1f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS idx_ycoin_evt_created')
    op.drop_index(op.f('idx_ycoin_user_created'), table_name='ycoin_transactions')
    op.drop_index(op.f('ix_ycoin_transactions_user_id'), table_name='ycoin_transactions')
    op.drop_table('ycoin_transactions')
    op.alter_column('tribe_activities', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('tribe_activities', 'location',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('tribe_activities', 'event_time',
               existing_type=sa.TIME(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('tribe_activities', 'image_urls',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('tribe_activities', 'creator_userid',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.drop_index(op.f('ix_tribe_activities_creator'), table_name='tribe_activities')
    op.drop_index(op.f('ix_tribe_activities_status'), table_name='tribe_activities')
    op.drop_index(op.f('ix_tribe_activities_activity_id'), table_name='tribe_activities')
    op.create_index(op.f('ix_tribe_activities_activity_id'), 'tribe_activities', ['activity_id'], unique=False)
    op.create_index(op.f('ix_tribe_activities_creator_userid'), 'tribe_activities', ['creator_userid'], unique=False)
    op.alter_column('user_profile', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user_profile', 'user_id',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user_profile', 'tribe',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('ix_user_profile_tribe_id'), table_name='user_profile')
    op.drop_index(op.f('uq_user_profile_user_id'), table_name='user_profile')
    op.drop_column('user_profile', 'tribe_set_at')
    op.drop_column('user_profile', 'tribe_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('tribe_id', sa.INTEGER(), nullable=True))
    op.add_column('user_profile', sa.Column('tribe_set_at', sa.DATETIME(), nullable=True))
    op.create_index(op.f('uq_user_profile_user_id'), 'user_profile', ['user_id'], unique=1)
    op.create_index(op.f('ix_user_profile_tribe_id'), 'user_profile', ['tribe_id'], unique=False)
    op.alter_column('user_profile', 'tribe',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('user_profile', 'user_id',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user_profile', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_index(op.f('ix_tribe_activities_creator_userid'), table_name='tribe_activities')
    op.drop_index(op.f('ix_tribe_activities_activity_id'), table_name='tribe_activities')
    op.create_index(op.f('ix_tribe_activities_activity_id'), 'tribe_activities', ['activity_id'], unique=1)
    op.create_index(op.f('ix_tribe_activities_status'), 'tribe_activities', ['status'], unique=False)
    op.create_index(op.f('ix_tribe_activities_creator'), 'tribe_activities', ['creator_userid'], unique=False)
    op.alter_column('tribe_activities', 'creator_userid',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('tribe_activities', 'image_urls',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tribe_activities', 'event_time',
               existing_type=sa.String(length=20),
               type_=sa.TIME(),
               existing_nullable=False)
    op.alter_column('tribe_activities', 'location',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('tribe_activities', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.create_table('ycoin_transactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('source_docid', sa.VARCHAR(length=255), nullable=True),
    sa.Column('context_docid', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('meta', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_type', 'context_docid', name=op.f('uniq_user_evt_ctx')),
    sa.UniqueConstraint('user_id', 'event_type', 'source_docid', name=op.f('uniq_user_evt_src'))
    )
    op.create_index(op.f('ix_ycoin_transactions_user_id'), 'ycoin_transactions', ['user_id'], unique=False)
    op.create_index(op.f('idx_ycoin_user_created'), 'ycoin_transactions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_ycoin_evt_created'), 'ycoin_transactions', ['event_type', 'created_at'], unique=False)
    # ### end Alembic commands ###
